// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var THREE = require("THREE");

console.log("Three.js BuckleScript binding r1");

var ratio = 400.0 / 400.0;

var scene = new THREE.Scene();

var camera = new THREE.PerspectiveCamera(45.0, ratio, 1.0, 1000.0);

var renderer = new THREE.WebGLRenderer();

exports.ratio = ratio;
exports.scene = scene;
exports.camera = camera;
exports.renderer = renderer;
/*  Not a pure module */
