// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_module = require("bs-platform/lib/js/caml_module.js");

var Scene = Caml_module.init_mod([
      "/Users/divertise/Dev/digitake.github.io/bs-three/src/Three.ml",
      6,
      10
    ], [[0]]);

Caml_module.update_mod([[0]], Scene, Scene);

var Camera = Caml_module.init_mod([
      "/Users/divertise/Dev/digitake.github.io/bs-three/src/Three.ml",
      16,
      10
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], Camera, Camera);

var WebGLRenderer = Caml_module.init_mod([
      "/Users/divertise/Dev/digitake.github.io/bs-three/src/Three.ml",
      23,
      10
    ], [[0]]);

Caml_module.update_mod([[0]], WebGLRenderer, WebGLRenderer);

exports.Scene = Scene;
exports.Camera = Camera;
exports.WebGLRenderer = WebGLRenderer;
/* Scene Not a pure module */
